### ISSUE TITLE
Questions regarding style transfer model.

### ISSUE THREAD

**Issue by boqchen** [nktoan/Causal-Inference-via-Style-Transfer-for-OOD-Generalisation#1]
Hi,

Thanks for the amazing work.

I have a question regarding which style transfer model to use during training. In the code I notices the style transfer model is loaded here (line #49) [https://github.com/nktoan/Causal-Inference-via-Style-Transfer-for-OOD-Generalisation/blob/main/imcls/trainers/causalfd.py](https://github.com/nktoan/Causal-Inference-via-Style-Transfer-for-OOD-Generalisation/issues/url).

`self.style_transfer_checkpoints_path = os.path.join(os.getcwd(), f"output_style_transfer/{self.learned_dataset}/{self.domain_test}/seed21/StyleTransfer Checkpoint.tar")`

I was wondering where is the StyleTransfer Checkpoint.tar file provided.

Thanks in advance!

**Comment by nktoan** [comment]
HI boqchen,

Apologies for the delayed response; I didn't receive a notification about your issue on GitHub. I've uploaded the pretrained weights (titled 'StyleTransfer Checkpoint.tar') for each dataset and domain. However, I recently realized that the weights for PACS were not uploaded correctly. I have now updated these weights. Please take another look and inform me if there are any more issues.

As mentioned in the readme file, all the pre-trained weights are uploaded here: https://drive.google.com/drive/folders/124eDQlk04VC0jsQNCzMe016px5f9hcbM

Thank you for your interest!
